blog/urls.py
from django.conf.urls import url
from django.urls import path
from .feeds import LatestPostFeed
from . import views

# App name
app_name = 'blog'

# Url Patterns
urlpatterns = [

    # Default lists all posts
    url('^$', views.post_list, name='post_list'),
    
    # List post by category
    path('category/<slug:category_slug>/', views.post_list, name = 'post_list_by_category'),
    
    # List post by tag
    path('tag/<slug:tag_slug>/', views.post_list, name = 'post_list_by_tag'),
    
    # List post by author
    path('author/<int:author_id>/', views.post_list, name = 'post_list_by_author'),

    # Read a post
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name = 'post_detail'),
    
    # Discussion
    path('discussion/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_discussion, name = 'post_discussion'),
    
    # Flatpage
    path('flatpage/<slug:slug>/', views.flatpage, name = 'flatpage'),

    # Search 
    path('search/', views.post_search, name = 'post_search'),

    # RSS Feed
    path('feed/', LatestPostFeed(), name = 'post_feed')
]

mysite/urls.py
from django.conf.urls import include, url
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import PostSiteMap, CategorySiteMap, TagSiteMap
from django.conf.urls.static import static
from . import settings 

sitemaps = {
    'posts': PostSiteMap,
    'categories': CategorySiteMap,
    'tags': TagSiteMap,
}

urlpatterns = [
    path('', include(('blog.urls', 'blogdefault'), namespace = 'blogdefault')),
    path('blog/', include(('blog.urls', 'blog'), namespace = 'blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name = 'django.contrib.settings.views.sitemap'),
]

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment
from django.utils.translation import gettext_lazy as _

class CommentForm(forms.ModelForm):
    """ Implements a form for a comment """
    class Meta:
        model = Comment 
        fields = ('name','email','body')
        forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mr-sm-2', 'placeholder': _('Search for...')}))

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment, Category, User, Tag, Flatpage
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView
from .forms import CommentForm, SearchForm
from django.contrib import messages
from .decorators import check_recaptcha
from django.urls import reverse
from django.db.models import Count
from django.db.models import Q
from django.apps import apps

#------------------------------------------

def post_search(request):
    """ Receives a query and posts results """

    form = SearchForm()
    query = None
    context = None 
    object_list = []
    meta_title = None
    meta_description = None

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            # String too short
            if(len(query) <= 3):
                messages.error(request, _('The search string was too short, please try again.'))
                response = redirect(reverse('blog:post_list'))
                return response

            meta_title = _('Search results for %(query)s') % {'query': query}
            meta_descriptions = _('Search results in posts for %(query)s') % {'query': query}
            object_list = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
            
    # Page and pagination
    paginator = Paginator(object_list, apps.get_app_config('Blog').pagination)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post_list.html',
                  {'form': form,
                  'query': query,
                  'meta_title': meta_title,
                  'search_string': '&query='+ query,
                  'meta_description': meta_description,
                  'page': page,
                  'posts': posts})

#------------------------------------------

def post_list(request, category_slug = None, tag_slug = None, author_id = None):
    """ Lists all posts, filtered by category and tag, and paginates the results """

    object_list = Post.published.all()
    category = None
    tag = None 
    author = None
    meta_title = None 
    meta_description = None 
    canonical = None

    # If category given
    if(category_slug):
        category = get_object_or_404(Category, slug = category_slug)
        object_list = object_list.filter(category__in=[category])
        canonical = request.build_absolute_uri(category.get_absolute_url())
        meta_description = category.description
        meta_title = category.name

    # If tag given
    if(tag_slug):
        tag = get_object_or_404(Tag, slug = tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        canonical = request.build_absolute_uri(tag.get_absolute_url())
        meta_description = "Posts tagged with "+ tag.name
        meta_title = tag.name

    # If author given
    if(author_id):
        author = get_object_or_404(User, id = author_id)
        object_list = object_list.filter(author__in=[author])
        canonical = request.build_absolute_uri(author.profile.get_absolute_url())
        meta_title = author.profile
        meta_description = "Posts published by "+ str(author.profile)
        
    # Page and pagination
    paginator = Paginator(object_list, apps.get_app_config('Blog').pagination) 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'page': page,
                                                        'posts': posts,
                                                        'meta_title': meta_title,
                                                        'meta_description': meta_description,
                                                        'canonical': canonical,
                                                        'category': category,
                                                        'author': author,
                                                        'tag': tag})

#------------------------------------------

def post_discussion(request, year, month, day, post):
    """ Displays the discussion for a given post """

    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)    
    
    # Recaptcha must be used?
    recaptcha_enabled =  apps.get_app_config('Blog').recaptcha_enabled
    
    # Comment defaults to none
    new_comment = None

    # Comment received via post
    if request.method == 'POST':

        # Instance comment form
        comment_form = CommentForm(data = request.POST)

        # Begin reCAPTCHA validation
        if(recaptcha_enabled): 
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': apps.get_app_config('Blog').recaptcha_secret,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
        else:   # No validation
            result = {'success': True}

        # Form must be valid and recaptcha too
        if(comment_form.is_valid() and result['success']):
            new_comment = comment_form.save(commit = False)
            new_comment.post = post 
            new_comment.save()
    # Not received comment yet
    else:
        comment_form = CommentForm()
    
    # Comments (we need to paginate this time)
    comment_count = Comment.objects.filter(post=post, active=True).count() 
    comments_display = apps.get_app_config('Blog').max_comments_discussion
    object_list = post.comments.filter(active = True).order_by('-created')
    
    # Page and pagination
    paginator = Paginator(object_list, comments_display) 
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        comments = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_discussion.html', {'post': post,
                                                              'page': page,
                                                              'comments': comments,
                                                              'comment_count': comment_count,
                                                              'new_comment': new_comment,
                                                              'recaptcha_enabled': recaptcha_enabled,
                                                              'comment_form': comment_form})
    

#------------------------------------------

def flatpage(request, slug):
    """ Displays a flatpage or raises a 404 error """

    page = get_object_or_404(Flatpage, slug = slug, status='published')
    host = request.scheme +"://"+ request.get_host();
    canonical = request.build_absolute_uri(page.get_absolute_url())
    return render(request, 'blog/flatpage.html', {'page': page,
                                                       'host': host, 
                                                       'canonical': canonical})

#------------------------------------------

@check_recaptcha
def post_detail(request, year, month, day, post):
    """ Displays a post or raises a 404 error """

    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)    

    # Comments
    comment_count = Comment.objects.filter(post=post, active=True).count() 
    comments_display = apps.get_app_config('Blog').max_comments_per_post
    comments = post.comments.filter(active = True).order_by('-created')[:comments_display]
    new_comment = None

    # Recaptcha must be used?
    recaptcha_enabled =  apps.get_app_config('Blog').recaptcha_enabled

    # Comment received via post
    if request.method == 'POST':

        # Instance comment form
        comment_form = CommentForm(data = request.POST)

        # Form must be valid and recaptcha too
        if(comment_form.is_valid() and request.recaptcha_is_valid):
            new_comment = comment_form.save(commit = False)
            new_comment.post = post 
            new_comment.save()

    # Not received comment yet
    else:
        comment_form = CommentForm()

    # Build canonical
    host = request.scheme +"://"+ request.get_host();
    canonical = request.build_absolute_uri(post.get_absolute_url())

    # Get similar posts
    post_tag_ids = post.tags.values_list('id', flat = True)  # Tag ids for this post

blog/templates/blog/_categories.html
{% load i18n %}
<!-- ==== Categories start ===== -->
<div class="card mt-0 mb-4">
    <h5 class="card-header">{% trans "Categories" %}</h5>
    <div class="card-body pl-0 pt-0 pr-0 pb-0">
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item d-flex justify-content-between align-items-center pl-4">
                    <a href="{{ category.get_absolute_url }}" class="text-dark">{{ category.name }}</a>
                     <span class="badge badge-secondary badge-pill">{{ category.get_post_count }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<!-- ==== Categories end ==== -->

blog/templates/blog/_search_box.html
{% load i18n %}
{% load blog_tags %}
<!-- ==== Search Start ===== -->
<form class="form-inline my-2 my-lg-0" action="{% url 'blog:post_search' %}" method="get">
    {% for field in form.visible_fields %}
        {{ field }}
    {% endfor %}
    <input type="submit" class="btn btn-secondary my-2 my-sm-0" value="{% trans 'Search' %}">
</form>
<!-- ==== Search End ==== -->

blog/templates/blog/_tags.html
{% load i18n %}
<!-- ==== Tags start ===== -->
<div class="card mt-0 mb-4">
    <h5 class="card-header">{% trans "Tags" %}</h5>
    <div class="card-body">
        <h6 class="h4 mb-0">
            {% for tag in tags %}
            <a href="{% url 'blog:post_list_by_tag' tag.name %}" class="badge badge-pill badge-light mb-2">#{{ tag.name }}</a> &nbsp;
            {% endfor %}
        <h6>
    </div>
</div>
<!-- ==== Tags end ==== -->

blog/templates/blog/post_detail.html
{% extends "blog/__l_base.html" %}
{% load i18n %}
{% load blog_tags %}
{% block title %}{{ post.get_meta_title|capfirst }} - {{ block.super }}{% endblock %}
{% block meta_description %}{{ post.get_meta_description }}{% endblock %}
{% block extra_head %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ post.get_meta_title }}"/>
    <meta property="og:description" content="{{ post.get_meta_description }}"/>
    <meta property="og:site_name" content="{% app_attr 'meta_title' %}"/>
    <meta property="article:author" content="{{ post.author.profile }}"/>
    {% for tag in post.tags.all %}
        <meta property="article:tag" content="{{ tag.name|capfirst }}"/>
    {% endfor %}
    <meta property="article:section" content="{{ post.category.name }}"/>
    <meta property="article:published_time" content="{{ post.publish }}"/>
    <meta property="article:modified_time" content="{{ post.updated }}"/>
    <meta property="og:updated_time" content="{{ post.created }}"/>
    {% if post.cover_image %}
        <meta property="og:image" content="{{ host }}{{ MEDIA_URL}}{{ post.cover_image }}"/>
    {% endif %}
    {% if canonical %}
        <meta property="og:url" content="{{ canonical }}"/>
        <link rel="canonical" href="{{ canonical }}" />
    {% endif %}
{% endblock %}

<!-- ==== Content Start ==== -->
{% block content %}

    <!-- ==== Schema Start ==== -->
    <script type="application/ld+json">
    {{ verbatim }} { {{ endverbatim }}
        "@context": "https://schema.org", 
        "@type": "BlogPosting",
        "headline": "{{ post.get_meta_title }}",
        "alternativeHeadline": "{{ post.title }}",
        {% if post.cover_image %}
        "image": "{{ host }}{{ MEDIA_URL }}{{ post.cover_image }}",
        {% endif %}
        "genre": "{{ post.category }}", 
        "keywords": "{{ post.tags.all|join:',' }}",
        "wordcount": "{{ post.body|wordcount }}",
        "publisher": "{% app_attr 'meta_title' %}",
        {% if canonical %}
        "url": "{{ canonical }}",
        {% endif %}
        "datePublished": "{{ post.publish|date:'Y-m-d' }}",
        "dateCreated": "{{ post.created|date:'Y-m-d' }}",
        "dateModified": "{{ post.updated|date:'Y-m-d' }}",
        "description": "{{ post.get_meta_description }}",
        "articleBody": "{{ post.body|markdown|striptags|truncatewords:50 }}",
        "author": 
        {{ verbatim }} { {{ endverbatim }}
            "@type": "Person",
            "name": "{{ post.author.profile }}"
        {{ verbatim }} } {{ endverbatim }}
    {{ verbatim }} } {{ endverbatim }}
    </script>
    <!-- ==== Schema End ==== -->

    <!-- ==== Post Start ==== -->
    <div class="card mt-0 mb-5">
        {% if post.cover_image %}
            <img class="card-img-top" src="{{ MEDIA_URL }}{{ post.cover_image }}" alt="{{ post.title|capfirst }}">
        {% endif %}
        <div class="card-body pl-5 pr-5 pb-4 pt-4">
            <h1 class="mb-4 mt-2 h2">{{ post.title|capfirst }}</h1>
            {{ post.body|markdown }}
            
            <!-- ==== Sharing Start ==== -->
            <p class="lead text-left mt-4">
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ canonical|urlencode }}" 
                    class="fa fa-facebook text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="https://twitter.com/home?status={{ canonical|urlencode }}" 
                    class="fa fa-twitter text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="https://pinterest.com/pin/create/button/?url={{ canonical|urlencode }}&amp;media=&amp;description={{ post.get_meta_description|urlencode }}" 
                    class="fa fa-pinterest text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="https://www.reddit.com/submit?url={{ canonical|urlencode }}" 
                    class="fa fa-reddit text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ canonical|urlencode }}&amp;title={{ post.get_meta_title|urlencode }}&summary={{ post.get_meta_description|urlencode }}&source=" 
                    class="fa fa-linkedin text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="https://profitquery.com/add-to/delicious/?url={{ canonical|urlencode }}&amp;title={{ post.get_meta_title|urlencode }}" 
                    class="fa fa-delicious text-dark align-middle" 
                    style="font-size: 25px; text-decoration: none;"></a> &nbsp;&nbsp;
                <a href="http://www.digg.com/submit?url={{ canonical|urlencode }}" 
                    class="fa fa-digg text-dark align-middle" 
                    target="_blank"
                    style="font-size: 25px; text-decoration: none;"></a>
            </p>
            <!-- ==== Sharing End ==== -->
            
            <!-- ==== Grid Image Gallery Start ==== -->
            {% if post.gallery %}
                <hr class="mt-5 mb-4"  />
                <div class="container">
                {% for field in post.gallery.get_all_images %}
                    {% cycle 'odd' 'even' as divbytwo silent %}
                    {% if divbytwo == 'odd' %}<div class="row">{% endif %}
                    <div class="col-sm pt-2 pb-2">
                        <a href="{{ MEDIA_URL }}{{ field }}" title="{{ post.title|capfirst }}">
                            <img class="img-fluid img-thumbnail" src="{{ MEDIA_URL }}{{ field }}" alt="{{ post.title|capfirst }}">
                        </a>
                    </div>
                    {% if divbytwo == 'even' %}</div>{% endif %}
                {% endfor %} 
                </div>
            {% endif %}
            <!-- ==== Grid Image Gallery End ==== -->
            
            <!-- ==== Similar Start ==== -->
            {% if similar_posts %}
                <hr class="mt-5 mb-0"  />
                <h4 class="mt-4 mb-3">{% trans "Related posts" %}</h4>
                <ul style="mb-0">
                {% for post in similar_posts %}
                    <li><a href="{{ post.get_absolute_url }}" class="text-muted" title="{{ post.title|capfirst }}">{{ post.title|capfirst }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
            <!-- ==== Similar End ==== -->
            

            <hr class="mt-5 mb-0"  />
            <h4 class="mt-4 mb-4">{% trans "Published by" %}</h4>
            <div class="media">
                <img width="80" src="{{ post.author.profile.get_avatar }}" class="mr-3 rounded" alt="{{ post.author.profile }}">
                <div class="media-body">
                    <h5 class="mt-0">
                        {{ post.author.profile }}
                    </h5>
                    <p>
                        {% if post.author.profile.bio %}
                            {{ post.author.profile.bio|linebreaksbr }} 
                        {% endif %}
                        <a class="text-muted" href="{% url 'blog:post_list_by_author' post.author.id %}">
                            {% trans "View all posts by" %} {{ post.author.profile }}
                            </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            {{ post.publish|date:"M d, Y" }} &nbsp;&nbsp;
            <span class="badge badge-secondary">
                <a href="{% url 'blog:post_list_by_category' post.category.slug %}" class="text-white">{{ post.category }}</a>
            </span>
            {% for tag in post.tags.all %}
                <span class="badge badge-light">
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="text-dark">#{{ tag.name }}</a>
                </span>
            {% endfor %}
        </div>
    </div>
    
    <!-- ==== Comments start ==== -->
    {% if comments.count > 0 %}
        <div class="card mt-0 mb-5">
            <div class="card-body pl-5 pr-5 pb-2 pt-4">
                <h2 class="mb-5 mt-3">
                {% if comment_count > 1 %}
                    {{ comment_count }} {% trans "Comments" %}
                {% else %}
                    {{ comment_count }} {% trans "Comment" %}
                {% endif %}
                </h2>
                <ul class="list-unstyled">
                {% for comment in comments %}
                    {% include "blog/_comment.html" %}
                {% endfor %}
                </ul>
                {% if comment_count > comments.count%}
                    <a href="{{ post.get_discussion_url }}" role="button" class="btn btn-secondary btn-block mt-4 mb-4">
                    {% trans "Go to discussion" %} ({{ comment_count }})</a>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <!-- ==== Comments End ==== -->

    <!-- ==== New Comment Start ==== -->
    {% if post.comments_enabled %}
        {% include "blog/_comment_form.html" %}
    {% endif %}
    <!-- ==== New Commend End ==== -->

{% endblock %}
<!-- ==== Content End ==== -->

blog/templates/blog/post_discussion.html
{% extends "blog/__l_base.html" %}
{% load i18n %}
{% load blog_tags %}
{% block title %}{% trans "Discussion" %}: {{ post.get_meta_title|capfirst }} - {{ block.super }}{% endblock %}
{% block meta_description %}{{ post.get_meta_description }}{% endblock %}
{% block extra_head %}
<meta name="robots" content="noindex" />
{% endblock %}

<!-- ==== Content Start ==== -->
{% block content %}
        
    <div class="card mt-0 mb-5">
        <div class="card-body pb-3">
            <h1 class="h2">{% trans "Discussion" %}</h1>
        </div>
    </div>
        
    <!-- === Post Info ==== -->
    <div class="card mt-0 mb-5 pt-4">
        <div class="media pl-4">
            {% if post.cover_image %}
                <img width="30%" src="{{ MEDIA_URL }}{{ post.cover_image }}" class="mr-3 rounded" alt="{{ post.title|capfirst }}">
            {% endif %}
            <div class="media-body pl-2 pr-4">
                <h2 class="mt-0 h3">{{ post.title|capfirst }}</h2>
                {% if post.body %}
                    <p>{{ post.body|markdown|striptags|truncatewords:40 }}</p>
                {% endif %}
            </div>
        </div>
        <div class="card-footer text-muted mt-3">
            {{ post.publish|date:"M d, Y" }} &nbsp;&nbsp;
            <span class="badge badge-secondary">
                <a href="{% url 'blog:post_list_by_category' post.category.slug %}" class="text-white">{{ post.category }}</a>
            </span>
            {% for tag in post.tags.all %}
                <span class="badge badge-light">
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="text-dark">#{{ tag.name }}</a>
                </span>
            {% endfor %}
        </div>
    </div>
    <!-- ==== Post Info End ==== -->

    <!-- ==== Comments start ==== -->
    {% if comment_count > 0 %}
        <div class="card mt-0 mb-5">
            <div class="card-body pl-5 pr-5 pb-2 pt-4 pb-4">
                <h2 class="mb-5 mt-3">{{ comment_count }} comment{{ comment_count|pluralize }}</h2>
                <ul class="list-unstyled">
                {% for comment in comments %}
                    {% include "blog/_comment.html" %}
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
    <!-- ==== Comments End ==== -->
    
    {% include "_pagination.html" with page=comments %}

    <!-- ==== New Comment Start ==== -->
    {% if post.comments_enabled %}
        {% include "blog/_comment_form.html" %}
    {% endif %}
    <!-- ==== New Commend End ==== -->

{% endblock %}
<!-- ==== Content End ==== -->

blog/templates/blog/post_list.html
{% extends "blog/__l_base.html" %}
{% load i18n %}
{% load blog_tags %}
{% block title %}{% if meta_title %}{{ meta_title|capfirst }} - {% endif %}{{ block.super }}{% endblock %}
{% block meta_description %}{% if meta_description %}{{ meta_description }}{% endif %}{% endblock %}
{% block extra_head %}
    {% if canonical %}
        <link rel="canonical" href="{{ canonical }}" />
    {% endif %}
{% endblock %}
{% block content %}
    {% if query %}
        <div class="card mt-0 mb-5">
            <div class="card-body pb-3">
                <h1 class="h2">{% trans "Search results for" %}: "{{ query|title }}"</h1>
            </div>
        </div>
    {% elif category %}
        <div class="card mt-0 mb-5">
            <div class="card-body pb-3">
                <h1 class="card-title h2">{% trans "Category" %}: {{ category.name|title }}</h1>
                {% if category.description %}
                <hr />
                <p class="lead">{{ category.description }}</p>
                {% endif %}
            </div>
        </div>
    {% elif author %}
        <div class="card mt-0 mb-5 pt-4 pl-4 pr-4 pb-2">
            <div class="media">
                <img width="100" src="{{ author.profile.get_avatar }}" class="mr-3 rounded" alt="{{ author.profile }}">
                <div class="media-body pl-2">
                    <h2 class="mt-0">
                        {{ author.profile }}
                    </h2>
                    {% if author.profile.bio %}
                    <p class="lead">{{ author.profile.bio|linebreaksbr }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% elif tag %}
        <div class="card mt-0 mb-5">
            <div class="card-body pb-3">
                <h1 class="card-title h2">{% trans "Tag" %}: {{ tag.name|title }}</h1>
            </div>
        </div>
    {% endif %}
    {% for post in posts %}
        <div class="card mt-0 mb-5">
            {% if post.cover_image %}
                <a href="{{ post.get_absolute_url }}" title="{{ post.title|capfirst }}">
                    <img class="card-img-top" src="{{ MEDIA_URL }}{{ post.cover_image }}" alt="{{ post.title|capfirst }}">
                </a>
            {% endif %}
            <div class="card-body pl-5 pr-5 pb-4 pt-4">
                <h2 class="card-title mt-2"><a href="{{ post.get_absolute_url }}" class="text-dark">{{ post.title|capfirst }}</a></h2>
                <p class="card-text mt-4">{{ post.body|markdown|striptags|truncatewords_html:50 }}</p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-light mt-4 mb-2"><strong>{% trans "Continue reading" %}</strong></a>
            </div>
            <div class="card-footer text-muted">
                    {{ post.publish|date:"M d, Y" }} &nbsp;&nbsp;
                    <span class="badge badge-secondary">
                        <a href="{% url 'blog:post_list_by_category' post.category.slug %}" class="text-white">{{ post.category }}</a>
                    </span>
                    {% for tag in post.tags.all %}
                        <span class="badge badge-light">
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="text-dark">#{{ tag.name }}</a>
                        </span>
                    {% endfor %}
            </div>
        </div>
    {% endfor %}
    {% include "_pagination.html" with page=posts %}
{% endblock %}